### ISSUE TITLE
在ARM芯片的Docker中无法正常跑起来

### ISSUE THREAD

**Issue by sbfkcel** [X-Profiler/xprofiler-docker#8]
容器会自动停掉

**Comment by hyj1991** [comment]
这个 docker 项目没有做 arm 版本，你要自己构建 arm 版本

**Comment by defaultjacky** [comment]
--platform=linux/amd64

**Comment by SageKwun** [comment]
> 

docker build -t easy-monitor --platform=linux/arm64/v8  .
